import React from 'react';

/* Stylesheets */
import { Grid, Paper, Table, TableBody, TableCell, TableRow, Tooltip } from '@material-ui/core';

const CashFlowHighlights = (props) => {
  const {
    statsObject,
  } = props;

  return (
    <div>
      <Paper style={{padding: '10px'}}>
        <Grid container>
          <Grid item xs={12}>
            <h3 style={{margin: '0px'}}>
              Cash Flow Highlights
            </h3>
          </Grid>
          <Grid item xs={12}>
            <Table>
              <TableBody>
                <TableRow>
                  <TableCell><div><Tooltip title={'Definition: Measure of the amount of cash generated by a companys normal business operations'} placement="right"><b style={{cursor: 'pointer'}}>Operating Cash Flow</b></Tooltip></div><small>over trailing 12 months</small></TableCell>
                  <TableCell>{statsObject['Operating Cash Flow (ttm)']}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell><div><Tooltip title={'Definition: Amount of cash a business has after it meets its financial obligations'} placement="right"><b style={{cursor: 'pointer'}}>Levered Free Cash Flow</b></Tooltip></div><small>most recent quarter</small></TableCell>
                  <TableCell>{statsObject['Levered Free Cash Flow (ttm)']}</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Grid>
        </Grid>
      </Paper>
    </div>
  )
}

export default CashFlowHighlights;